<?php
/**
 * @link http://www.php-devil.ru/
 * @copyright Copyright (c) 2017 Web Wizardry
 * @license http://www.php-devil.ru/license/
 */

namespace PhpDevil\database\mysql;

class Schema extends \PhpDevil\database\generic\Schema
{
    public static function getColumnClass()
    {
        return SchemaColumn::class;
    }

    public static function setDefaults($column)
    {
        $type = $column->type;
        if ('string' == $type) {
            if (isset($column->params['char'])) $column->type = 'char';
            else $column->type = 'varchar';
            if (!$column->size) $column->size = 255;
        }

        if ('integer' == $type) {
            $column->type = 'int';
            if (!$column->size) $column->size = 11;
        }

        return parent::setDefaults($column); // TODO: Change the autogenerated stub
    }

    public function getCreateTableQuery()
    {
        $sql = 'create table `' . $this->_tableName. '` (';
        $delimiter = "\n\t";
        foreach ($this->_columns as $k=>$col) {
            $sql .= $delimiter . '`' . $k . '` ' . $col;
            $delimiter = ",\n\t";
        }
        if ($this->_primaryKey) {
            $sql .= $delimiter . 'primary key (`' . implode('`, `', $this->_primaryKey) . '`)';
            $delimiter = ",\n\t";
        }
        if (!empty($this->_keys)) foreach ($this->_keys as $name=>$param) {
            $sql .= $delimiter;
            if (SchemaColumn::K_INDEX === $param[0]) $sql .= 'key `' . $name . '` ';
            if (SchemaColumn::K_UNIQUE === $param[0]) $sql .= 'unique key `' . $name . '` ';
            $sql .= '(`' . $param[1] . '`)';
        }
        $sql .= ')';
        if (!empty($this->_tableOptions)) $sql .= ', ' . $this->_tableOptions;
        return $sql;
    }
}