<?php
/**
 * @link http://www.php-devil.ru/
 * @copyright Copyright (c) 2017 Web Wizardry
 * @license http://www.php-devil.ru/license/
 */

namespace PhpDevil\database\mysql;

class Schema extends \PhpDevil\database\generic\Schema
{
    public static function getColumnClass()
    {
        return SchemaColumn::class;
    }

    public static function setDefaults($column)
    {
        $type = $column->type;
        if ('string' == $type) {
            if (isset($column->params['char'])) $column->type = 'char';
            else $column->type = 'varchar';
            if (!$column->size) $column->size = 255;
        }

        if ('integer' == $type) {
            $column->type = 'int';
            if (!$column->size) $column->size = 11;
        }

        return parent::setDefaults($column); // TODO: Change the autogenerated stub
    }
}